// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE

import * as Block from "../node_modules/bs-platform/lib/es6/block.js";
import * as VNode$Bluedom from "../src/VNode.bs.js";

var match = document.getElementById("root");

if (!(match == null)) {
  VNode$Bluedom.mount(match, VNode$Bluedom.reify(/* Component */Block.__(2, [/* HTML */Block.__(0, [
                  "div",
                  /* :: */[
                    /* Id */["demo"],
                    /* [] */0
                  ],
                  /* :: */[
                    /* Text */Block.__(1, ["Hello, World!"]),
                    /* [] */0
                  ]
                ])])));
}

export {
  
}
/* match Not a pure module */
