// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE

import * as Block from "../node_modules/bs-platform/lib/es6/block.js";
import * as VNode$Bluedom from "../src/VNode.bs.js";

var match = document.getElementById("root");

if (!(match == null)) {
  VNode$Bluedom.reify(/* DomNode */[
        "div",
        /* :: */[
          /* Id */Block.__(0, ["demo"]),
          /* :: */[
            /* TextContent */Block.__(1, ["Hello, World!"]),
            /* [] */0
          ]
        ],
        /* [] */0
      ], match);
}

export {
  
}
/* match Not a pure module */
