// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE

import * as Belt_List from "../node_modules/bs-platform/lib/es6/belt_List.js";
import * as Pervasives from "../node_modules/bs-platform/lib/es6/pervasives.js";

function applyProp(elm, property) {
  if (property.tag) {
    elm.textContent = property[0];
    return /* () */0;
  } else {
    elm.id = property[0];
    return /* () */0;
  }
}

function reify(vNode, domNode) {
  if (vNode) {
    var elm = document.createElement(vNode[0]);
    Belt_List.forEach(vNode[1], (function (param) {
            return applyProp(elm, param);
          }));
    var parent = domNode.parentNode;
    if (parent == null) {
      Pervasives.failwith("NoParent");
    } else {
      parent.insertBefore(elm, domNode);
      parent.removeChild(domNode);
    }
    return /* () */0;
  } else {
    return /* () */0;
  }
}

export {
  applyProp ,
  reify ,
  
}
/* No side effect */
